### ISSUE TITLE
mkpsxiso: Directories with the same name are merged even if their path is different

### ISSUE THREAD

**Issue by G4Vi** [CookiePLMonster/mkpsxiso#21]
`iso::DirTreeClass::AddSubDirEntry` is setup to skip duplicate directories, but only checks name, not path.

This leads to be cases where multiple subdirectories are merged into the the same one. i.e

`GAME/AUDIO`, `KIOSK/AUDIO`, and `TITLE/AUDIO` being merged into `GAME/AUDIO` in the output iso. (Vib-Ribbon)

**Comment by CookiePLMonster** [comment]
Fixed with #22
