### ISSUE TITLE
Missing files when rebuilding certain games

### ISSUE THREAD

**Issue by mateusfavarin** [CookiePLMonster/mkpsxiso#25]
Some files don't build when using mkpsxiso.

Repro case: use dumpsxiso on Crash Team Racing (PAL) `sha256: AF7FDE1DE43C7771E269768DCF9D03FC4759DB0ECF5D441D50325E7EBB3B3E20`, and then rebuild the disc with mkpsxiso using the automated XML from dumpsxiso. The disc built will be missing most XA files in `XA/LANG/*.XA` folders. Note that dumpsxiso can correctly identify and extract the files, but mkpsxiso fails to build them into the disc.

**Comment by CookiePLMonster** [comment]
Just checking - does https://github.com/CookiePLMonster/mkpsxiso/pull/24 fix it?

**Comment by mateusfavarin** [comment]
Built the `develop` branch locally and tested on the game. XA files are still missing after rebuilding. If it helps, the game file structure for the XA files is:

`XA/DCH/EXTRA/*.XA`
`XA/DCH/GAME/*.XA`
`XA/ENG/EXTRA/*.XA`
`XA/ENG/GAME/*.XA`
...

Every XA file in `XA/DCH/*` is correctly built, but other XAs from other folders are missing.

**Comment by CookiePLMonster** [comment]
Confirmed solved with https://github.com/Lameguy64/mkpsxiso/commit/9f6275f08829ea9de8122c8232a019e8724acbbd.
