### ISSUE TITLE
dumpsxiso doesn't handle gaps in the lba's / pregaps

### ISSUE THREAD

**Issue by G4Vi** [CookiePLMonster/mkpsxiso#6]
Trying to figure out why the size of repacking a dumpsxiso dump using mkpsxiso of SLUS-00005 (Rayman [US]) didn't match, I discovered neither the ISO9660 filesystem nor the cue file can be trusted in order to make an accurate dump. There is no guarantee the LBA of the next file begins where the last file ended. The pregap in the cue file doesn't always account for this data either.

In the case of Rayman, the `MUS3` entry ends at LBA 41535. The next entry is `MUS1/GENE.RAW` at LBA 41835. That's a gap of 300 sectors. The cue file however only shows a pregap of 150 seconds (2 seconds starting at 09:15:60 (LBA 41685)). Those unaccounted for 150 sectors  starting at LBA 41435 aren't blank too, it starts with `00 FF FF FF FF FF FF FF FF FF FF 00 09 15 60 02`.

For proper preservation of pregaps and other parts of a disk, I think the lba gaps should be dumped, perhaps to a files named `dumpsxiso_gap_STARTSECTOR.raw` where STARTSECTOR is the start of the unreferenced data, that mkpsxiso could pack right into the iso.

All of this was tested with https://github.com/CookiePLMonster/mkpsxiso/tree/xml-attribute-propagation and modifying dumpsxiso as below to dump out the lbas.	 

```
// Sort files by LBA for "strict" output
entries.sort([](const auto& left, const auto& right)
	{
		return left.entry.entryOffs.lsb < right.entry.entryOffs.lsb;
	});

unsigned expectedLBA = 0;
for (auto& entry : entries)
{
	if(expectedLBA != 0)
	{
		if(entry.entry.entryOffs.lsb != expectedLBA)
		{
			printf("GOT GAP size (in sectors): %u\n", entry.entry.entryOffs.lsb - expectedLBA);
		}
	}
	printf("Entry lba %u entrySize %u %s %s ", entry.entry.entryOffs.lsb, entry.entry.entrySize.lsb, entry.virtualPath.c_str(), entry.identifier.c_str());
	printTimecode(entry.entry.entryOffs.lsb);		
	expectedLBA = entry.entry.entryOffs.lsb + ((entry.entry.entrySize.lsb+2047)/2048);
}
exit(1);
```
[rayman_merged.cue.txt](https://github.com/CookiePLMonster/mkpsxiso/files/7687228/rayman_merged.cue.txt)
[rayman_lba.log](https://github.com/CookiePLMonster/mkpsxiso/files/7687230/rayman_lba.log)

**Comment by G4Vi** [comment]
I began a branch to gap handling as such here: https://github.com/G4Vi/mkpsxiso/tree/try_fix_rayman

Nothing has been done in mkpsxiso yet, but a preliminary implementation is in dumpsxiso. This version dumps the gaps as `dumpsxiso_gap_STARTSECTOR.raw` inside of the `entry.virtualPath` of the subsequent file.

Also a `pregap` element has been added to the file element for DA tracks. `duration` specifies the length of the pregap in MM:SS:FF. A default value of "00:02:00" is assumed. A value of "00:00:00" means no pregap. `pregap-data` MUST refer to the previous sibling element of the file (another file). If the `pregap-data` element IS NOT present silence data of `duration` will be padded in.

Example:

```XML
<dir name="MUS1">
    <file name="dumpsxiso_pad_41535.raw" source="merged/MUS1/dumpsxiso_pad_41535.raw" type="da" gmt_offs="0" xa_perm="0" xa_gid="0" xa_uid="0"/>
    <file name="GENE.RAW" source="merged/MUS1/GENE.RAW" type="da" gmt_offs="36" xa_perm="1365" xa_gid="0" xa_uid="0">
        <pregap duration="00:02:00" pregap-data="dumpsxiso_pad_41535.raw"/>
    </file>
    <file name="dumpsxiso_pad_42535.raw" source="merged/MUS1/dumpsxiso_pad_42535.raw" type="da" gmt_offs="0" xa_perm="0" xa_gid="0" xa_uid="0"/>
    <file name="JUNGLE1.RAW" source="merged/MUS1/JUNGLE1.RAW" type="da" gmt_offs="36" xa_perm="1365" xa_gid="0" xa_uid="0">
        <pregap duration="00:02:00" pregap-data="dumpsxiso_pad_42535.raw"/>
    </file>
```

**Comment by CookiePLMonster** [comment]
Do note I still wish to add `<dummy>` entries dumping to dumpsxiso when LBA order is specified to be preserved, this will likely heavily overlap with whatever you're doing to them. Good call on the pregap ideas though.

**Comment by G4Vi** [comment]
A `<dummy>` entry works for me instead of a hacked `<file>` entry for the outside file data, Is the plan there to just dump it to disk similarly to the `dumpsxiso_gap_STARTSECTOR.raw` or verify if it's all 0's and if it's not then dump it, or something different?

**Comment by CookiePLMonster** [comment]
I have not considered dumping, but maybe it makes sense if data is nonzero. Are there known valid discs that have nonzero data in daps?

**Comment by G4Vi** [comment]
SLUS-00005 (Rayman [US]), hash checked with redump, is one such disc as mentioned above.  Between LBA 41535 and LBA 41685 is unaccounted for space starting with `00 FF FF FF FF FF FF FF FF FF FF 00 09 15 60 02`. The pregap for the first DA track starts at LBA 41685.

**Comment by CookiePLMonster** [comment]
Isn't this just the control blocks though, and the actual data is zeroes?

**Comment by G4Vi** [comment]
Looking closer, that sounds right, a similar header appears after 2352 bytes. I don't know enough about CDs or iso9660 to say. Maybe those can be recreated without dumping to disk. I think mkpsxiso just wrote 0s when I tried to repack instead of control data.
Edit: Upon learning more about CD-ROM, I see it's the start of a CD-ROM Mode 2 Sector sync and header.

I'm all for denoting that in the xml file if that's the case to not waste disk, just want to achieve bit exact replication. Without using a cue file, data between DA tracks can reasonable be assumed to be pregaps, however due to not knowing when the pregap of the first DA track starts if any, I think a generic data dump entity like `dumpsxiso_gap_STARTSECTOR.raw` makes sense.

Should potential pregap data be stored any differently? We could write the 2 seconds before each track as wav file instead of referring to just the LBA gap dumped without headers?

**Comment by CookiePLMonster** [comment]
I have implemented basic gap detection in 1aa12f3963e16f12b7749c6b7a9ffc5c6a790e96, do you think it's fine? Right now it won't replicate Rayman's gaps perfectly yet, since they have nonzero data in the control block. I will most likely have to add some basic inspection of those gaps to determine if they need form1/form ECC or nothing.

**Comment by G4Vi** [comment]
Thanks, That should reduce most if not all cases of the output image size being the wrong size.

To keep the XML writing cleaner and ensure the gap detection is done even if xml isn't written , do you think it makes sense to do it right after `SaveLicense`? I realize it was messy in my branch to hack it into `ExtractFiles`. Doing it before does however still require some dummy `cd::IsoDirEntries::Entry` entries for the various cases of zero and nonzero data.

**Comment by CookiePLMonster** [comment]
Where would you output the gap data if XML is not written though? In the way it's done currently, it does not output any files.

**Comment by G4Vi** [comment]
> Where would you output the gap data if XML is not written though? In the way it's done currently, it does not output any files.

Most of the time they wouldn't be written, only when they are non-zero. I'd write it to the directory of the following file. In the case of *Rayman*, if the pregap to `GENE.RAW` was non-zero, the pregap would be written to the `MUS1` dir.

**Comment by CookiePLMonster** [comment]
> only when they are non-zero

Maybe my approach for this is **too** pragmatic, but I'd rather not think about this too much until we find a valid disc that has such data in a gap. For now I need to implement gaps with ECC/EDC, that should take care of discs like Rayman.

**Comment by G4Vi** [comment]
`dumpsxiso` now attempts to guess the pregap instead of hardcoding the pregaps to 150 sectors since https://github.com/CookiePLMonster/mkpsxiso/pull/13

Closing this as gaps are not unhandled anymore, however cue file support and ECC/EDC detection will improve gap handling.
