### ISSUE TITLE
Unifying DA tracks with regular CDDA tracks

### ISSUE THREAD

**Issue by G4Vi** [CookiePLMonster/mkpsxiso#7]
Currently mkpsxiso packs DA tracks completely separately from CDDA tracks. Looking at adding the miniaudio support to the da tracks, I think it makes sense to unify them.  In order to unify them, I propose making DA tracks correspond to CDDA tracks in a backwards compatible way in the xml tree. This also properly keeps pregaps outside of the `<directory_tree>` / iso 9660 file system and the complexity out of the `<file>` element. 

```xml
<iso_project image_name="hello_cdda.bin" cue_sheet="hello_cdda.cue">
 <track type="data">       
    <directory_tree>
        <file name="GENE.RAW" source="merged/MUS1/GENE.RAW" type="da" gmt_offs="36" xa_perm="1365" xa_gid="0" xa_uid="0"/>
    </directory_tree>
 </track>
</isoproject>
```

would evaluate to the same as
```xml
<iso_project image_name="hello_cdda.bin" cue_sheet="hello_cdda.cue">
 <track type="data">       
    <directory_tree>
        <file name="GENE.RAW" trackid="02" type="da" gmt_offs="36" xa_perm="1365" xa_gid="0" xa_uid="0"/>
    </directory_tree>
 </track>
 <track type="audio" trackid="02" source="merged/MUS1/GENE.RAW" >
    <pregap duration="00:02:00"/>
 </track>
</isoproject>
```
The `trackid` attribute is just to make it clear which CDDA track corresponds with the DA file, it is not necessarily the actual track number.

Supporting parsing the new syntax or not this would make it so there to be only one code path for CUE writing and CDDA packing.

**Comment by CookiePLMonster** [comment]
A few remarks:
* `trackid` should actually be a transparent string, so could very well be `trackid="foobarmeow"`
* `trackid` should be mutually exclusive with `source` on that `file` element.

I think the general idea makes sense though. However, there still needs to be something done so "legacy" DA tracks also use the same code path as CDDA packing, IMO. It shouldn't be too hard though.

**Comment by G4Vi** [comment]
All working here https://github.com/CookiePLMonster/mkpsxiso/pull/13. For verification nothing in the iso was changed, I repacked Rayman with it and https://github.com/CookiePLMonster/mkpsxiso/commit/1aa12f3963e16f12b7749c6b7a9ffc5c6a790e96 and the hash came out the same.

**Comment by G4Vi** [comment]
All done #13 is merged.
